# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # 10MB limit
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # Black - Code formatter
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.11

  # Ruff - Linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # mypy - Type checking (optional, puede ser lento)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.14.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]

  # isort - Import sorting (ya incluido en Ruff, pero se puede usar separado)
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black"]

  # Jupyter notebook cleanup
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys', 'metadata.kernelspec metadata.language_info']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

# Configuration for specific hooks
default_language_version:
  python: python3.11

# Files to exclude
exclude: |
  (?x)^(
      \.git/|
      \.dvc/|
      \.mypy_cache/|
      \.pytest_cache/|
      \.ruff_cache/|
      __pycache__/|
      \.venv/|
      venv/|
      build/|
      dist/|
      .*\.egg-info/|
      mlruns/|
      notebooks/.*\.ipynb$
  )
